# Generated by Django 4.0.4 on 2022-05-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
