# Generated by Django 4.0.4 on 2022-05-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_contact_desc_remove_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.TextField(default='5555555555'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=5555555555, max_length=12),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=122),
        ),
    ]
